CREATE TABLE tb_cliente (
	id_cliente INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
	nome_cliente VARCHAR(100) NOT NULL,
	cpf_cliente VARCHAR(11) NOT NULL UNIQUE,
    rg_cliente	VARCHAR(15) NOT NULL UNIQUE,
    titulo_eleitor_cliente  VARCHAR(12) NOT NULL UNIQUE,
    num_contato_cliente VARCHAR(11),
    email_cliente VARCHAR(100) UNIQUE,
    dt_nascimento_cliente date NOT NULL,
	ultimo_valor_cobrado_cliente decimal(10,2)
);

CREATE TABLE USERS (
    USERNAME VARCHAR(50) PRIMARY KEY,
    PASSWORD VARCHAR(255) NOT NULL,
    ENABLED CHAR(1) NOT NULL
);


CREATE TABLE AUTHORITIES (
    USERNAME VARCHAR(50) NOT NULL,
    AUTHORITY VARCHAR(50) NOT NULL
);

ALTER TABLE AUTHORITIES ADD CONSTRAINT AUTHORITIES_UNIQUE UNIQUE (USERNAME, AUTHORITY);
ALTER TABLE AUTHORITIES ADD CONSTRAINT AUTHORITIES_FK1 FOREIGN KEY (USERNAME) REFERENCES USERS (USERNAME);